services:
  postgres:
    container_name: 'cdb-service-postgres'
    image: 'postgres:16.1'
    environment:
      - 'POSTGRES_DB=cdb-service'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5433:5432'
