services:
  postgres:
    container_name: 'customer-wallet-postgres'
    image: 'postgres:16.1'
    environment:
      - 'POSTGRES_DB=cdb-service'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5434:5432'
