services:
  postgres:
    container_name: 'customer-postgres'
    image: 'postgres:16.1'
    environment:
      - 'POSTGRES_DB=customer'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
